import { NextRequest, NextResponse } from "next/server";
import {
  ensureLists,
  searchCard,
  createCard,
  updateCard,
  getBoardLists,
} from "@/lib/trello";
import type { SEOOpportunity } from "@/types/analytics";

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatPct(n: number) {
  return `${(n * 100).toFixed(2)}%`;
}

function formatNum(n: number) {
  return n.toLocaleString("en-GB");
}

const TYPE_LABELS: Record<string, string> = {
  "quick-win": "Quick Win 🎯",
  "ctr-improvement": "CTR Fix ✏️",
  "position-boost": "Position Boost 🚀",
};

/** Build a Markdown description for a Trello card */
function buildDesc(op: SEOOpportunity): string {
  const lines = [
    `## ${op.query}`,
    ``,
    `**Type:** ${TYPE_LABELS[op.opportunityType] ?? op.opportunityType}`,
    `**Position:** #${op.position.toFixed(1)}`,
    `**Impressions:** ${formatNum(op.impressions)}`,
    `**CTR:** ${formatPct(op.ctr)}`,
    `**Clicks:** ${formatNum(op.clicks)}`,
    `**Potential Extra Clicks:** +${formatNum(op.potentialClicks)}`,
    ``,
    `### Recommendation`,
    op.recommendation,
  ];

  if (op.page) {
    lines.push(``, `### Page`, op.page);
  }

  lines.push(
    ``,
    `---`,
    `*Auto-generated by Cawarden Analytics Dashboard*`,
  );

  return lines.join("\n");
}

// ── GET — verify config + ensure lists exist ──────────────────────────────────

export async function GET() {
  const boardId = process.env.TRELLO_BOARD_ID;
  const hasKey = Boolean(process.env.TRELLO_API_KEY);
  const hasToken = Boolean(process.env.TRELLO_TOKEN);

  if (!boardId || !hasKey || !hasToken) {
    return NextResponse.json(
      {
        configured: false,
        missing: [
          !hasKey && "TRELLO_API_KEY",
          !hasToken && "TRELLO_TOKEN",
          !boardId && "TRELLO_BOARD_ID",
        ].filter(Boolean),
      },
      { status: 503 },
    );
  }

  try {
    const lists = await ensureLists(boardId);
    const allLists = await getBoardLists(boardId);
    return NextResponse.json({ configured: true, boardId, lists, allLists });
  } catch (err) {
    return NextResponse.json({ configured: false, error: String(err) }, { status: 500 });
  }
}

// ── POST — push a single SEOOpportunity to Trello ─────────────────────────────

export async function POST(req: NextRequest) {
  const boardId = process.env.TRELLO_BOARD_ID;
  if (!boardId || !process.env.TRELLO_API_KEY || !process.env.TRELLO_TOKEN) {
    return NextResponse.json(
      { error: "Trello credentials not configured. Add TRELLO_API_KEY, TRELLO_TOKEN and TRELLO_BOARD_ID to .env.local." },
      { status: 503 },
    );
  }

  let op: SEOOpportunity;
  try {
    op = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!op.query || !op.opportunityType) {
    return NextResponse.json({ error: "Missing required fields: query, opportunityType" }, { status: 400 });
  }

  try {
    // Ensure the three lists exist and get their IDs
    const lists = await ensureLists(boardId);
    const listId = lists[op.opportunityType];

    if (!listId) {
      return NextResponse.json(
        { error: `Unknown opportunityType: ${op.opportunityType}` },
        { status: 400 },
      );
    }

    const desc = buildDesc(op);

    // Look for an existing card with the same keyword name
    const existing = await searchCard(boardId, op.query);

    let card;
    let action: "created" | "updated";

    if (existing) {
      // Update description + move to the correct list (in case type changed)
      card = await updateCard(existing.id, { desc, idList: listId });
      action = "updated";
    } else {
      card = await createCard(listId, op.query, desc);
      action = "created";
    }

    return NextResponse.json({
      cardId: card.id,
      cardUrl: card.shortUrl,
      action,
    });
  } catch (err) {
    console.error("[Trello push error]", err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
